using System.Text.Json;
using System.Text.Json.Nodes;
using ApiTestGen.Api.Models;

namespace ApiTestGen.Api.Services;

/// <summary>
/// Builds a Postman v2.1 collection from the generated test cases. Doing this deterministically (instead of
/// asking the model for raw Postman JSON) guarantees the collection always imports cleanly and matches the
/// test cases exactly.
/// </summary>
public static class PostmanCollectionBuilder
{
    public const string SchemaUrl = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json";
    public const string DefaultBaseUrl = "http://localhost:8080";

    private static readonly JsonSerializerOptions IndentedJson = new() { WriteIndented = true };

    public static JsonObject Build(string title, string? baseUrl, IReadOnlyList<TestCase> testCases)
    {
        var folders = new JsonArray();
        AddFolder(folders, "Positive tests", testCases.Where(t => t.Category == TestCategory.Positive));
        AddFolder(folders, "Negative tests", testCases.Where(t => t.Category == TestCategory.Negative));

        return new JsonObject
        {
            ["info"] = new JsonObject
            {
                ["_postman_id"] = Guid.NewGuid().ToString(),
                ["name"] = title,
                ["description"] = "Generated by APITestGen. Set the baseUrl and authToken collection variables before running.",
                ["schema"] = SchemaUrl,
            },
            ["item"] = folders,
            ["variable"] = new JsonArray(
                Variable("baseUrl", baseUrl ?? DefaultBaseUrl),
                Variable("authToken", "")),
        };
    }

    private static void AddFolder(JsonArray folders, string name, IEnumerable<TestCase> testCases)
    {
        var items = new JsonArray();
        foreach (var testCase in testCases)
            items.Add(BuildItem(testCase));

        if (items.Count > 0)
            folders.Add(new JsonObject { ["name"] = name, ["item"] = items });
    }

    private static JsonObject BuildItem(TestCase tc)
    {
        var segments = new JsonArray();
        foreach (var segment in tc.Path.Split('/', StringSplitOptions.RemoveEmptyEntries))
            segments.Add(segment);

        var raw = "{{baseUrl}}" + tc.Path;
        if (tc.QueryParams.Count > 0)
            raw += "?" + string.Join("&", tc.QueryParams.Select(kv => $"{kv.Key}={kv.Value}"));

        var url = new JsonObject
        {
            ["raw"] = raw,
            ["host"] = new JsonArray("{{baseUrl}}"),
            ["path"] = segments,
        };
        if (tc.QueryParams.Count > 0)
            url["query"] = KeyValues(tc.QueryParams);

        var headers = KeyValues(tc.Headers);
        if (tc.Body is not null && !tc.Headers.Keys.Any(k => k.Equals("Content-Type", StringComparison.OrdinalIgnoreCase)))
            headers.Add(new JsonObject { ["key"] = "Content-Type", ["value"] = "application/json" });

        var request = new JsonObject
        {
            ["method"] = tc.Method,
            ["header"] = headers,
            ["url"] = url,
            ["description"] = tc.Description,
        };

        if (tc.Body is { } body)
        {
            request["body"] = new JsonObject
            {
                ["mode"] = "raw",
                ["raw"] = body.ValueKind == JsonValueKind.String ? body.GetString() : JsonSerializer.Serialize(body, IndentedJson),
                ["options"] = new JsonObject { ["raw"] = new JsonObject { ["language"] = "json" } },
            };
        }

        var exec = new JsonArray();
        foreach (var line in TestScript(tc))
            exec.Add(line);

        return new JsonObject
        {
            ["name"] = $"{tc.Id} {tc.Title}",
            ["request"] = request,
            ["event"] = new JsonArray(new JsonObject
            {
                ["listen"] = "test",
                ["script"] = new JsonObject { ["type"] = "text/javascript", ["exec"] = exec },
            }),
        };
    }

    private static IEnumerable<string> TestScript(TestCase tc)
    {
        yield return $"pm.test(\"{EscapeJs(tc.Id)}: status code is {tc.ExpectedStatus}\", function () {{";
        yield return $"    pm.response.to.have.status({tc.ExpectedStatus});";
        yield return "});";

        if (tc.Assertions.Count == 0)
            yield break;

        yield return "// Further checks from the test design:";
        foreach (var assertion in tc.Assertions)
            yield return "// - " + assertion.ReplaceLineEndings(" ");
    }

    private static JsonArray KeyValues(IReadOnlyDictionary<string, string> values)
    {
        var array = new JsonArray();
        foreach (var (key, value) in values)
            array.Add(new JsonObject { ["key"] = key, ["value"] = value });
        return array;
    }

    private static JsonObject Variable(string key, string value) =>
        new() { ["key"] = key, ["value"] = value, ["type"] = "string" };

    private static string EscapeJs(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
